### ISSUE TITLE
1.2 Definición de prototipos

### ISSUE THREAD

**Issue by JoelPulidoG** [ISWPOLI/old_school#10]
**Descripción**
Hacer los prototipos generales de la aplicación, esto permitirá tener una referencia de lo planteado en los requerimientos de manera gráfica.

**Tareas:**
- [x] Generar mock-ups
- [x] Subir mock-ups

**Comment by mpcamacho1** [comment]
[MockUps y diseño del aplicativo.pdf](https://github.com/ISWPOLI/old_school/files/1443755/MockUps.y.diseno.del.aplicativo.pdf)
Se adjuntan los mockups de cada modulo del proyecto "Project History
[PresentacionMockups_Proyecto.pptx](https://github.com/ISWPOLI/old_school/files/1443754/PresentacionMockups_Proyecto.pptx)
"
