### ISSUE TITLE
2.1 Realizar modelo relacional

### ISSUE THREAD

**Issue by amdiazbe** [ISWPOLI/old_school#4]
**Descripción**
Hacer análisis y creación del modelo relacional de base de datos, con tablas, campos y relaciones entre sí.

**Tareas:**
- [x] Definir tablas
- [x] Definir campos de la tabla
- [x] Definir relaciones
- [x] Generar modelo (Imagen)

**Comment by mpcamacho1** [comment]
Se realiza el Modelo relacional de la base de datos, tablas principales y relaciones.
![mr](https://user-images.githubusercontent.com/31083627/29900963-d6cf7a80-8dba-11e7-8d68-c33ca408513c.PNG)

**Comment by mpcamacho1** [comment]
![mr_project_history](https://user-images.githubusercontent.com/31083627/30066222-dc806d16-921c-11e7-9a2b-a4ed4130f549.PNG)

Adjunto Modelo Relacional  generado desde MYSQ.

**Comment by JoelPulidoG** [comment]
Última versión del MER.

![mer final](https://user-images.githubusercontent.com/10676334/33106936-c5da7598-cf02-11e7-8219-3aa2f762caed.png)
