### ISSUE TITLE
1.6 Documento de planeación

### ISSUE THREAD

**Issue by JoelPulidoG** [ISWPOLI/old_school#47]
**Descripción**
Crear documento de planeación del proyecto. En las tareas se describe cuáles son los temas que debe contener el documento.

**Tareas:**
- [x] History Mapping y Cronograma
- [x] Perfilado del equipo de trabajo

**Comment by mpcamacho1** [comment]
[Cronograma_de_Actividades.xlsx](https://github.com/ISWPOLI/old_school/files/1282146/Cronograma_de_Actividades.xlsx)
Se adjunta archivo con el perfilado 

del equipo y el cronograma de cada una de las actividades a desarrollar

**Comment by mpcamacho1** [comment]
[CronogramaActividades.xlsx](https://github.com/ISWPOLI/old_school/files/1282926/CronogramaActividades.xlsx)


Se adjunta desarrollo history mapping
