### ISSUE TITLE
1.7 Documento técnico

### ISSUE THREAD

**Issue by JoelPulidoG** [ISWPOLI/old_school#48]
**Descripción**
Crear documento técnico del proyecto. En las tareas se describe cuáles son los temas que debe contener el documento.

**Tareas:**
**_- Arquitectura del sistema_**
- [x] Diagrama de infraestructura
- [ ] Estilos: Diagrama de capas –diagrama componentes
- [x] De Conectores, Interfaces (protocolos-Tivadis)
- [x] De las Herramientas y frameworks

**_- Patrones de diseño_** 
- [x] Explicación 
- [x] Diagrama UML de patrones

**Comment by mpcamacho1** [comment]
Documentacion tecnica diseño del proyecto.
[Documentacion-Diseño_ProjectHistory.pdf](https://github.com/ISWPOLI/old_school/files/1347740/Documentacion-Diseno_ProjectHistory.pdf)

**Comment by mpcamacho1** [comment]
Se completa documentacion tecnica de diseño del proyecto.
[Documento-Tecnica_Diseño_ProjectHistory.pdf](https://github.com/ISWPOLI/old_school/files/1443751/Documento-Tecnica_Diseno_ProjectHistory.pdf)
