### ISSUE TITLE
1.9 Documento Pruebas de carga y Estres

### ISSUE THREAD

**Issue by mpcamacho1** [ISWPOLI/old_school#65]
Descripción
Esta sección contiene los procesos relacionados con el proceso de pruebas de carga y estres  del sistema para verificar su rendimiento.

Tareas

Documento pruebas Carga/estres

**Comment by amdiazbe** [comment]
[Pruebas_Carga_Estres_Sistema.pdf](https://github.com/ISWPOLI/old_school/files/1469060/Pruebas_Carga_Estres_Sistema.pdf)
