### ISSUE TITLE
2.1 Documento Pruebas Codigo Fuente

### ISSUE THREAD

**Issue by mpcamacho1** [ISWPOLI/old_school#67]
Descripción

Esta sección contiene documentación de pruebas del código fuente utilizado en el proyecto.

Tareas

- [x] Documento pruebas Código fuente.

**Comment by JoelPulidoG** [comment]
Se añaden documentos de revisión de código.

[Revisión de código v1.0.docx](https://github.com/ISWPOLI/old_school/files/1489642/Revision.de.codigo.v1.0.docx)
[Resultados análisis completo código Java v1.0.pdf](https://github.com/ISWPOLI/old_school/files/1489643/Resultados.analisis.completo.codigo.Java.v1.0.pdf)
