### ISSUE TITLE
3. Montaje de ambiente

### ISSUE THREAD

**Issue by jrmontanez** [ISWPOLI/old_school#7]
**Descripción**
Esta sección contiene las historias relacionadas con el proceso de montaje de ambiente

**Comment by JoelPulidoG** [comment]
Se da por cerrada esta Épica, pues se cerraron todas las tareas relacionadas con el montaje del ambiente. A continuación se listan las características del sistema, en cuanto a desarrollo:
**Características del Sistema**
- Java 1.8
- **Framework diseño:** JSF 2.2
- **Framework diseño:** Primefaces 6.1
- **Framework diseño:** Bootsfaces 1.1.3
- **Framework BD:** JPA 2.5.2
- **API:** EJB
- **Base de datos:** MySql
