### ISSUE TITLE
1.1 Definición de requerimientos

### ISSUE THREAD

**Issue by JoelPulidoG** [ISWPOLI/old_school#9]
**Descripción**
Definir y listar los requerimientos del proyecto

**Tareas:**
- [x] Hacer lista de requerimientos

**Comment by mpcamacho1** [comment]
Se realiza analisis general del proyecto describiendo la necesidad principal a solucionar.
[PresentacionProyecto.pptx](https://github.com/ISWPOLI/old_school/files/1265429/PresentacionProyecto.pptx)

**Comment by jrmontanez** [comment]
[Esquema de referencia proyecto(1).docx](https://github.com/ISWPOLI/old_school/files/1283210/Esquema.de.referencia.proyecto.1.docx)
